# Generated by Django 5.2.1 on 2025-06-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.proveedor'),
        ),
    ]
